export const PREFIJOS_TELEFONO: { codigo: string; pais: string }[] = [
  { codigo: "+34", pais: "España" },
  { codigo: "+351", pais: "Portugal" },
  { codigo: "+33", pais: "Francia" },
  { codigo: "+49", pais: "Alemania" },
  { codigo: "+39", pais: "Italia" },
  { codigo: "+44", pais: "Reino Unido" },
  { codigo: "+353", pais: "Irlanda" },
  { codigo: "+31", pais: "Países Bajos" },
  { codigo: "+32", pais: "Bélgica" },
  { codigo: "+41", pais: "Suiza" },
  { codigo: "+43", pais: "Austria" },
  { codigo: "+30", pais: "Grecia" },
  { codigo: "+45", pais: "Dinamarca" },
  { codigo: "+46", pais: "Suecia" },
  { codigo: "+47", pais: "Noruega" },
  { codigo: "+358", pais: "Finlandia" },
  { codigo: "+48", pais: "Polonia" },
  { codigo: "+40", pais: "Rumanía" },
  { codigo: "+36", pais: "Hungría" },
  { codigo: "+420", pais: "República Checa" },
  { codigo: "+1", pais: "EE. UU. / Canadá" },
  { codigo: "+52", pais: "México" },
  { codigo: "+54", pais: "Argentina" },
  { codigo: "+55", pais: "Brasil" },
  { codigo: "+56", pais: "Chile" },
  { codigo: "+57", pais: "Colombia" },
  { codigo: "+58", pais: "Venezuela" },
  { codigo: "+51", pais: "Perú" },
  { codigo: "+593", pais: "Ecuador" },
  { codigo: "+591", pais: "Bolivia" },
  { codigo: "+595", pais: "Paraguay" },
  { codigo: "+598", pais: "Uruguay" },
  { codigo: "+506", pais: "Costa Rica" },
  { codigo: "+507", pais: "Panamá" },
  { codigo: "+503", pais: "El Salvador" },
  { codigo: "+502", pais: "Guatemala" },
  { codigo: "+504", pais: "Honduras" },
  { codigo: "+505", pais: "Nicaragua" },
  { codigo: "+53", pais: "Cuba" },
  { codigo: "+1809", pais: "República Dominicana" },
  { codigo: "+212", pais: "Marruecos" },
  { codigo: "+213", pais: "Argelia" },
  { codigo: "+216", pais: "Túnez" },
  { codigo: "+20", pais: "Egipto" },
  { codigo: "+90", pais: "Turquía" },
  { codigo: "+7", pais: "Rusia" },
  { codigo: "+86", pais: "China" },
  { codigo: "+81", pais: "Japón" },
  { codigo: "+82", pais: "Corea del Sur" },
  { codigo: "+91", pais: "India" },
  { codigo: "+61", pais: "Australia" },
  { codigo: "+64", pais: "Nueva Zelanda" },
];

export function parseTelefono(telefono: string | null | undefined): { prefijo: string; numero: string } {
  if (!telefono) return { prefijo: "+34", numero: "" };
  const match = telefono.trim().match(/^(\+\d{1,4})\s*(.*)$/);
  if (match) return { prefijo: match[1], numero: match[2] };
  return { prefijo: "+34", numero: telefono.trim() };
}
